### ISSUE TITLE
Please rename install_modules.h

### ISSUE THREAD

**Issue by miteshkumarsavita** [Bvangoor/Operating-Systems-506#2]
Hi Bharath,

please rename your shell script at https://github.com/Bvangoor/Operating-Systems-506/tree/master/HomeWork2/hw2-bvangoor/fs/amfs to install_modules.sh.

Regards,
Mitesh

**Comment by Bvangoor** [comment]
Hey Mitesh,

Thanks for the catch, I really appreciate. But it doesn't matter for the bash whether it is `sh'' or`h''. So I never got an issue while I'm testing. Anyways I'll change for better readability :).

Thanks,
Bharath.
